on:
  workflow_dispatch:
    inputs:
      blue:
        description: 'Enables blue deployment'
        required: true
        type: choice
        options:
          - true
          - false
      green:
        description: 'Enables green deployment'
        required: true
        type: choice
        options:
          - true
          - false
      trafficDistribution:
        description: 'Traffic distribution of blue/green deployment'
        required: true
        type: choice
        options:
          - blue
          - blue-90
          - split
          - green-90
          - green

name: Blue-Green Deployment for WebApp

jobs:
  cd:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color -var 'traffic_distribution=${{ inputs.trafficDistribution }} ' -auto-approve
